### PR TITLE
Update li-clean-seal.html

### PR DESCRIPTION
**Pull request by Kistine**
correct value field

### CODE REVIEW

**Review by Kistine — COMMENTED** [review]
@timwis - I added the "type": "!=" and changed the value to value= "" but the chart is not loading: https://data.phila.gov/visualizations/li-clean-seal

Should I give up or is there something easy and obvious I need to change in the json?

**Comment by timwis** [comment]
Hm, when I remove the 'where' entirely, I'm not getting any blank values; just nulls. To filter out nulls, you'd do:

```
          "type": "is not",
            "value": null
         }
```

Did you try that?

**Comment by timwis** [comment]
btw, if you go into the browser's developer tools when you load the vizwit page, then click on the network tab, you can see the failed request (it's red). If you go to the 'response' subtab, it will show you the error from carto:

```
invalid input syntax for type timestamp: \"\"
```

Screenshot 2020-05-06 at 13 46 19


If you look at the details of the request (in the headers or params subtab), it will give you the URL, which contains the SQL that vizwit actually generated:

```sql
SELECT count(*) as value,
       date_trunc('month', workordercompleteddate) as label 
FROM clean_seal
WHERE (workordercompleteddate != '')
GROUP BY date_trunc('month', workordercompleteddate)
ORDER BY label 
```

Judging by the error, it looks like the issue is that the WHERE clause is comparing a timestamp field to a string, which must be invalid for some reason 🤔  But `IS NOT NULL` seems to work.

**Comment by Kistine** [comment]
@timwis - The` IS NOT NULL` worked!! Thanks so much for taking the time to look at that and suggest how to resolve. And, especially, for sharing on the developer tools tidbits. You knew I'd want to know that :D

**Comment by timwis** [comment]
Great! Happy to help :)

**Pull request merged**
